### ISSUE TITLE
Suggestion: Include command-line interface

### ISSUE THREAD

**Issue by gregfurman** [sosedoff/ansible-vault-go#8]
Think it would be useful to include a (simple) command-line interface for this tool. Previously had to import this and manually create a CLI, so the ability to `go install` would circumvent that.

Nothing too complicated, just creating a `main.go` and using `flag` for parsing args would suffice.

Thoughts? Also happy to take this on 😄

**Comment by sosedoff** [comment]
The main reason why this package was originally created is to bring vault support to the application code, since the Ansible vault project does not provide any Go bindings. So having its own CLI in this repo defeats the purpose, at least for me, I would still use the standard `ansible-vault` CLI to manage data and make sure both sides work correctly.

If you're not using the ansible cli for managing secrets, may i ask what is your use case then?

**Comment by gregfurman** [comment]
We have a service that allows for any user in our org to encrypt secrets for PROD or DEV via a web-app (Goland backend). Currently, we use your package for encrypting and verifying secrets. Was wanting to instead run this serverlessly and just include a call to a binary as opposed to running an http client.

I suppose I could just use the `ansible-vault` cli but I like how lightweight this package is, and the functionality it provides fits our use-case perfectly.

**Comment by sosedoff** [comment]
That sounds reasonable. Do you have any supporting code for the feature?

**Comment by sosedoff** [comment]
Closing for now.
